filebeat.registry.path: /usr/share/filebeat/data/registry

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*.json
  json.keys_under_root: true
  json.add_error_key: true
  processors:
    - decode_json_fields:
        fields: ["message"]
        target: ""
        overwrite_keys: true
        add_error_key: true

output.logstash:
  hosts: ["logstash:5044"]

setup.template.name: "box"
setup.template.pattern: "box-*"
