# Use uma imagem base do Python
FROM python:3.9-slim

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia os arquivos necessários para o diretório de trabalho no contêiner
COPY . /app

# Instala as dependências necessárias
RUN pip install requests

# Comando para executar a aplicação
CMD ["python", "app.py"]
